# HVDNet Services
# Bootstrap icons: https://icons.getbootstrap.com/
#
- name: Fundamental Physical Constants
  description: >
    A semantic gateway to the latest and historical physical fundamental constants published 
    by [NIST](https://physics.nist.gov/cuu){target="_blank" rel="noopener"} 
    and [CODATA](https://codata.org/initiatives/data-science-and-stewardship/fundamental-physical-constants/){target="_blank" rel="noopener"}.
    A collaborative effort supported by the CODATA [Digital Representation of Units of Measurement (DRUM)](https://codata.org/initiatives/task-groups/drum/){target="_blank" rel="noopener"} Task Group.
  tags:
    - CODATA
    - DRUM
    - API
    - SI
  url: https://api.codata.org/drum/constants/
  github: https://github.com/codata/drum-constants-api
  icon: bi-rulers

- name: HVDNet File Manager
  description: >
    Web based application and API to manage your project files in the High-Value Data Network environment.
    To be used with our APIs and other FAIRification services.
    Contact support@highvaluedata.net for a free account.
  tags:
    - Application
    - Storage
    - Sharing
  url: https://files.highvaluedata.net
  icon: bi-folder

- name: FAIR Proxy API
  description: >
    API services to proxy and transform popular public platforms metadata into FAIR standard formats.
    Initial support focuses on [Socrata](https://www.socrata.com){target="_blank" rel="noopener"}
    (a.k.a. [Data Insights](https://www.tylertech.com/solutions/transformative-technology/data-insights){target="_blank" rel="noopener"}), 
    used by many city/state agencies and other data stewards in North America and beyond.
  tags:
    - API
    - FAIRification
    - Socrata
    - DCAT
    - DDI
    - Croissant
  coming_soon: true
  icon: bi-arrow-left-right

- name: Rich Data Services
  description: >
    A public instance of [Rich Data Services](https://www.richdataservices.com){target="_blank" rel="noopener"} hosted by the HVDN.
    Provides access to popular public high-value datasets for showcasing or demo purposes.
    Sponsored by [Metadata Technology North America](https://metadatatechnology.com){target="_blank" rel="noopener"}.
  tags:
    - API
    - Data
    - Metadata
    - FAIR
    - DDI-C
  coming_soon: true
  icon: bi-bar-chart-line
